MusicManager/Controllers/CreateController.cs
using System.IO;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MusicManager.BusinessLogic.Services;
using MusicManager.DataBase.Entities;

namespace MusicManager.Controllers
{
	public class CreateController : Controller
	{
		private readonly IService _createService;

		public CreateController(IService createservice)
		{
			_createService = createservice;
		}

		public ActionResult Add()
		{
			return View("Add");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CreateAlbum(Album model, HttpPostedFileBase coverfile)
		{
			if (model == null || !ModelState.IsValid) return Redirect("Error");
			if (coverfile != null)
			{
				string fileName = Path.GetFileName(coverfile.FileName);
				coverfile.SaveAs(Server.MapPath("~/Content/img/covers/" + fileName));
				model.AlbumCover = fileName;
			}
			await _createService.CreateThis(model);
			return RedirectToAction("ViewLibrary", "Library");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CreateArtist(Artist model)
		{
			if (model == null || !ModelState.IsValid) return Redirect("Error");
			await _createService.CreateThis(model);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CreateGenre(Genre model)
		{
			if (model == null || !ModelState.IsValid) return Redirect("Error");
			await _createService.CreateThis(model);
			return RedirectToAction("Index", "Home");
		}

	}
}

MusicManager/Views/Create/Add.cshtml
@{
	ViewBag.Title = "Add new";
}

<div class="row">
	<div class="container">
		<ol class="breadcrumb">
			<li>@Html.ActionLink("Home", "Index", "Home")</li>
			<li>@Html.ActionLink("Library", "ViewLibrary", "Library")</li>
			<li class="active">Add new</li>
		</ol>
	</div>
</div>
<div class="tabbable"> 
	<ul class="nav nav-tabs">
		<li class="active"><a href="#tab1" data-toggle="tab">Album</a></li>
		<li><a href="#tab2" data-toggle="tab">Artist</a></li>
		<li><a href="#tab3" data-toggle="tab">Genre</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
			@Html.Partial("View")
		</div>
		<div class="tab-pane" id="tab2">
			@Html.Partial("AddArtist")
		</div>
		<div class="tab-pane" id="tab3">
			@Html.Partial("AddGenre")
		</div>
	</div>
</div>

MusicManager/Views/Create/AddArtist.cshtml
@model MusicManager.DataBase.Entities.Artist

@using (Html.BeginForm("CreateArtist", "Create", null)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArtistName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MusicManager/Views/Create/AddGenre.cshtml
@model MusicManager.DataBase.Entities.Genre

@using (Html.BeginForm("CreateGenre", "Create", null)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MusicManager/Views/Create/View.cshtml
@model MusicManager.DataBase.Entities.Album

@using (Html.BeginForm("CreateAlbum", "Create", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Add Album</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.AlbumRating, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AlbumRating, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AlbumRating, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.AlbumYear, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AlbumYear, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AlbumYear, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.AlbumCover, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<div class="file_picker">
					<input type="file" name="coverfile"/>
				</div>
				@Html.ValidationMessageFor(model => model.AlbumCover, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}